python3 -m verl.trainer.main_es \
data.train_files=$DATA_DIR/tiny_train.parquet \
data.val_files=$DATA_DIR/tiny_test.parquet \
data.train_batch_size=32 \
data.val_batch_size=1312 \
data.max_prompt_length=256 \
data.max_response_length=1024 \
actor_rollout_ref.model.path=$BASE_MODEL \
actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP_SIZE \
actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
+actor_rollout_ref.model.torch_dtype=bfloat16 \
trainer.population_size=64 \
trainer.noise_std=0.02 \
trainer.learning_rate=0.05 \
trainer.total_generations=2 \
trainer.print_every=2 \
trainer.logger=['wandb'] \
+trainer.val_before_train=False \
trainer.default_hdfs_dir=null \
trainer.n_gpus_per_node=$N_GPUS \
trainer.nnodes=1 \
trainer.save_freq=-1 \
trainer.test_freq=-1 \
trainer.project_name=urop \
trainer.experiment_name=$EXPERIMENT_NAME \
trainer.default_local_dir=$CKPT_DIR
